SSH_HOST=tes3mp-server
PLUGINS_DIR=/home/mikhail/Projects/morrowind-modpack/plugins/
SERVER_SCRIPTS_DIR=/home/mikhail/Projects/morrowind-modpack/server-scripts/
CLIENT_SCRIPTS_DIR=/home/mikhail/Projects/morrowind-modpack/client-scripts/
